### ISSUE TITLE
"enhanced-mode: redir-host" is deprecated.

### ISSUE THREAD

**Issue by francisafu** [mahdibland/V2RayAggregator#13]
Hi,

Since "enhanced-mode: redir-host" is deprecated in Clash Core 2023.02.16 Premium (65211), only "fake-ip" is available to use, the Clash profiles are all broken when importing to Clash clients.

Please consider changing the "enhanced-mode: redir-host" to "enhanced-mode: fake-ip" at /update/provider/config.yml, line 22.

Thanks.

**Comment by mahdibland** [comment]
Done.
Thanks
