### ISSUE TITLE
Could you please provide sub/yml for high-speed node high-speed nods too?

### ISSUE THREAD

**Issue by hamedsbt** [mahdibland/V2RayAggregator#5]
Hi, thank you for your awsome try.
Could you please provide sub/yml for high-speed node high-speed nods too?

**Comment by mahdibland** [comment]
Hi, they already exist.
you can find them below "Instructions & Usage" section on the readme page

![image](https://user-images.githubusercontent.com/42766108/213130007-65a55d30-ee7e-4358-9531-021c9284ff54.png)

**Comment by mehdifirefox** [comment]
ببخشید تاپیک جدید باز نکردم
ممنون عالیه
فقط تعداد سرور ها خیلی بالاست 
این تو کامپیوتر هنگ میکنه چه برسه به گوشی

واسه کلش هم خطا میده 
proxy 1179: TLS must be true with h2/grpc network 

واسه v2rayn هم واسه چه اپراتوری شما تست کردید من بیشترشو تست میکنم سرورها کار نمیکنه
