### ISSUE TITLE
different subscriptions for vmess, shadowsocks and trojan

### ISSUE THREAD

**Issue by shahram10715** [mahdibland/V2RayAggregator#8]
Would you please create different subscription links for vmess, shadowsocks and trojan? Having too many servers makes my client very slow, besides that I can only connect to vmess servers.

**Comment by mahdibland** [comment]
> Would you please create different subscription links for vmess, shadowsocks and trojan? Having too many servers makes my client very slow, besides that I can only connect to vmess servers.

Added.
you can find subscription links for each protocol on the Readme page. let me know if you need base64 format too

![image](https://user-images.githubusercontent.com/42766108/215156472-bdd45a82-d195-450e-89c0-6eb6a3f5077c.png)

**Comment by shahram10715** [comment]
Thanks a lot. added to my matsuri. No I don't need base64 format. And I guess you can close this issue.
Once again thanks for gathering all these links.
